# Use container-based infrastructure
sudo: false

language: scala

scala:
   - 2.10.4

jdk:
  - openjdk7

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

env:
  # This splits the build into two parts
  matrix:
    - TEST_COMMAND="publishLocal sbtapidocjs/scripted core/test"

script:
  - sbt ++$TRAVIS_SCALA_VERSION $TEST_COMMAND


  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm