sudo: false

language: scala

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

matrix:
  include:
    - env: SBT_VERSION="1.0.0"
      jdk: openjdk8

    - env: SBT_VERSION="1.2.8"
      jdk: openjdk8

    - env: SBT_VERSION="1.2.8"
      jdk: openjdk11

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "^^${SBT_VERSION}" test scripted

jobs:
  include:
    - stage: release
      script: sbt ci-release

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
