# Use container-based infrastructure
sudo: false

language: scala
scala:
   - 2.10.4

jdk:
  - openjdk7

script: sbt ++$TRAVIS_SCALA_VERSION test scripted

# Tricks to avoid unnecessary cache updates
 - find $HOME/.sbt -name "*.lock" | xargs rm
 - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm